import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import NavBar from "@/components/layout/NavBar";
import { JetBrains_Mono, Inria_Sans } from "next/font/google";
import BackGround from "@/components/layout/BackGround";
import Footer from "@/components/layout/Footer";

const jetbrains = JetBrains_Mono({
  subsets: ["latin"], // or add others
  weight: ["400", "700"],
  variable: "--font-jetbrains",
  display: "swap", // optional
});
const inria = Inria_Sans({
  subsets: ["latin"], // or add others
  weight: ["400", "700"],
  variable: "--font-inria-sans",
  display: "swap", // optional
});

export const metadata: Metadata = {
  title: "Mnemonic Lock",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${jetbrains.variable} ${inria.variable}`}
    >
      <head />

      <body className="overflow-x-hidden">
        <ThemeProvider>
          <BackGround />
          <NavBar />
          <div className="min-h-screen flex flex-col">
            <div className="flex-grow"> {children}</div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
